// fonts
import { geistMono, geistSans } from '@/app/_libs/fonts'

// components
import { Header } from '@/app/_components/molecules/header'
import { Footer } from '@/app/_components/molecules/footer'

// styles
import './globals.css'

// types
import type { FC, ReactNode } from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Apply Digital | Store',
  icons: { icon: '/favicon.svg' },
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <html lang='en'>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <main className='flex flex-col flex-1 gap-8 min-h-screen'>
        <Header />
        <div className='w-full flex flex-col items-center px-4'>{children}</div>
        <Footer />
      </main>
    </body>
  </html>
)

export default RootLayout
