// fonts
import { geistMono, geistSans } from '@/app/_libs/fonts'

// styles
import './globals.css'

// types
import type { FC, ReactNode } from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Apply Digital | Store',
  icons: { icon: '/favicon.svg' },
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <html lang='en'>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      {children}
    </body>
  </html>
)

export default RootLayout
