name: 'QA Process'

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the dev branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Actions
        uses: actions/cache@v3
        id: restore-node-modules
        with:
          path: ./node_modules
          key: ${{ github.sha }}
          restore-keys: |
            node-modules-

      - name: Cache cypress binary
        uses: actions/cache@v3
        id: restore-cypress-binary
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ github.sha }}

  lint-projects:
    name: Run lint
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Actions
        uses: actions/cache@v3
        id: restore-node-modules
        with:
          path: ./node_modules
          key: ${{ github.sha }}

      - name: Running Lint
        run:
          npm run lint

  build-projects:
    name: Run build
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Actions
        uses: actions/cache@v3
        id: restore-node-modules
        with:
          path: ./node_modules
          key: ${{ github.sha }}

      - name: Build projects
        run:
          npm run build

  run-cypress:
    name: "Run Cypress"
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Actions
        uses: actions/cache@v3
        id: restore-node-modules
        with:
          path: ./node_modules
          key: ${{ github.sha }}

      - name: Cache cypress binary
        uses: actions/cache@v3
        id: restore-cypress-binary
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ github.sha }}

      - name: Run test
        run: npm run test:run